swagger: '2.0'
info:
  description: 'Avaliação Prática Lemobs'
  version: '1.0.0'
  title: Desafio API Lemobs - PAULO HENRIQUE LOURENÇO

basePath: /v1/

consumes:
  - application/json
produces:
  - application/json

schemes:
  - http

paths:

  # ---
  # Serviço responsável por cadastrar um novo usuário.
  # ---  
  /usuario:
    x-swagger-router-controller: usuario
    post:
      tags:
        - Usuário
      summary: "Adiciona um novo usuário"
      operationId: cadastrar_usuario
      parameters:
        - in: body
          name: body
          description: Modelo de Usuário
          required: true
          schema:
            $ref: "#/definitions/usuario"        
      responses:
        '201':
          description: Criado (Created)
        '400':
          description: Requisição Inválida (Bad Request)
        '500':
          description: Erro Interno do Servidor (Internal Server Error)    
    get:
      tags:
        - Usuário
      summary: "Retorna todos os usuário cadastrados"
      operationId: "listar_usuarios"
      responses:
        '200':
          description: Ok
        '400':
          description: Requisição Inválida (Bad Request)
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro Interno do Servidor (Internal Server Error)

  /usuario/{usuario_id}:
    x-swagger-router-controller: usuario
    put:
      tags:
        - Usuário
      summary: "Atualiza usuário pelo ID"
      operationId: editar_usuario
      parameters:
        - name: usuario_id
          in: path
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          required: true
          schema:
            $ref: "#/definitions/usuario" 
      responses:
        '200':
          description: Editado
        '400':
          description: Requisição Inválida (Bad Request)
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
    get:
      tags:
        - Usuário
      summary: "Busca usuário pelo ID"
      operationId: "buscar_usuario"
      parameters:
        - name: usuario_id
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: Encontrado
        '400':
          description: Requisição Inválida (Bad Request)
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro Interno do Servidor (Internal Server Error)

  /usuario/{usuario_id}/endereco:
    x-swagger-router-controller: endereco
    get:
      tags:
        - Usuário
        - Endereço
      summary: "Retorna a quantidade e os endereços do usuário"
      operationId: "listar_enderecos_usuario"
      parameters:
        - name: usuario_id
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        '200':
          description: Encontrado
        '400':
          description: Requisição Inválida (Bad Request)
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
                  
  /endereco:
    x-swagger-router-controller: endereco
    post:
      tags:
        - Endereço
      summary: "Adiciona um novo endereço"
      operationId: cadastrar_endereco
      parameters:
        - in: body
          name: body
          description: Modelo de Endereço
          required: true
          schema:
            $ref: "#/definitions/endereco"        
      responses:
        '201':
          description: Criado (Created)
        '400':
          description: Requisição Inválida (Bad Request)
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
    get:
      tags:
        - Endereço
      summary: "Retorna todos os endereços cadastrados"
      operationId: "listar_enderecos"
      parameters:
        - in: query
          name: bairro
          description: Bairro para a ser filtrado
          type: string
          required: false
      responses:
        '200':
          description: Ok
        '400':
          description: Requisição Inválida (Bad Request)
        '404':
          description: Usuário não encontrado
        '500':
          description: Erro Interno do Servidor (Internal Server Error)
            
  /docs:
    x-swagger-pipe: swagger_raw
    
definitions:
  usuario:
    type: object
    properties:
      nome:
        type: string
      data_nascimento:
        type: string
        format: date
      cpf:
        type: string
    required:
      - nome
      - data_nascimento
      - cpf
      
  endereco:
    type: object
    properties:
      rua:
        type: string
      numero:
        type: integer
        format: int64
      complemento:
        type: string
      bairro:
        type: string
      usuario_id:
        type: integer
        format: int64
    required:
      - rua
      - bairro
      - usuario_id